### ISSUE TITLE
Command for running RuboCop

### ISSUE THREAD

**Issue by jhsu802701** [novu/whale-of-a-tale#8]
What are the commands for running other tasks, such as seeding the database and running things like RuboCop, Rails Best Practices,Railroady, Rails-ERD, etc.?

**Comment by arich** [comment]
In the above PR, I added rubocop. You can check out that branch, `make sh web` to get into your web container, and run rubocop as normal. 

I find it easier to work inside a container as normal. Others make extensive use of the makefile and various commands we provide there. 

You could also look into the [DIP](https://github.com/bibendi/dip) gem we mentioned in the presentation. 

Since this is just a demo app, there's a database but no tables beyond the `schema_migrations` table. Running `docker-compose run --rm web rake db:create db:migrate` is all you need to get going. If we had db seed files, you could run them in the same way, `docker-compose run --rm web rake db:seed` (as you've already figured out).
