### ISSUE TITLE
Non-root user in Docker environment

### ISSUE THREAD

**Issue by jhsu802701** [novu/whale-of-a-tale#9]
Is there a non-root user in this Docker environment?  If not, should there be one?

I tried entering the Docker container with "docker-compose run --rm web /bin/sh".  The "whoami" command showed that I was running as root.   Is this a problem?  I'm used to doing most tasks (including running bundle/rake/rails commands) as a regular user.

**Comment by arich** [comment]
You're totally right! We do not run as root in our real applications, as it's a security risk. Lots more on this here: https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b

The primary purpose of this app is to demonstrate a basic docker rails app and provide a readable example without going into too many details that could overwhelm a docker newbie. 

This bit is debian flavored rather than alpine, but this is roughly what we do on other apps:
```dockerfile
ARG APP=app_name
ARG APP_NUMBER=1001
RUN addgroup --gid $APP_NUMBER --system $APP && \
    adduser --uid $APP_NUMBER --system $APP --ingroup $APP
USER $APP
```
